### PR TITLE
Added Xcode project for iOS framework

### PR DESCRIPTION
**Pull request by sundance2000**
An Xcode project was added to provide a framework for iOS, which can be imported easily into other projects. It may be necessary to modify the project to allow it being added to OS X or tvOS projects. This may also affect the podspec file.

### CODE REVIEW

**Comment by Esqarrouth** [comment]
Thanks for the second pull request. Its still giving a conflict error, why is that?

**Comment by sundance2000** [comment]
I merged the recent changes into my feature branch. Does it work now?

**Comment by Esqarrouth** [comment]
Worked perfect :ok_hand: 
I was also planning to add a little sample ViewController to show how it works. 

I will update the podspec file soon

**Comment by sundance2000** [comment]
I`m glad it finally worked.
An example file would be nice, especially to explain the configuration.

**Comment by Esqarrouth** [comment]
I updated the files order and added an example project. I hope I didn't mess anything up in your framework

**Comment by sundance2000** [comment]
Everything is still working fine, thank you for the information.

**Pull request merged**
