### PR TITLE
Mac OS X support

### PR DESCRIPTION
**Pull request by konradzdunczyk**

### CODE REVIEW

**Comment by konradzdunczyk** [comment]
Now I see I fixed bug which wasn't bug ;)

**Comment by Esqarrouth** [comment]
:) Would you like to revert that last commit before merging?

**Comment by konradzdunczyk** [comment]
Sure but I can't do it until Monday. Happy Holidays

**Comment by Esqarrouth** [comment]
Sure, no hurries unless someone requests it anyways. Happy holidays to you aswell

**Comment by Esqarrouth** [comment]
Thanks :+1:

**Pull request merged**
